Traceback (most recent call last):
  File "/lcrc/project/LCRC_for_DUNE/users/fathima/2x2_sim/run-larnd-sim/larnd-sim/./simulate_pixels.py", line 688, in <module>
    fire.Fire(run_simulation)
  File "/home/ffathimamaha/.local/swing/anaconda3/2023-01-11/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ffathimamaha/.local/swing/anaconda3/2023-01-11/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ffathimamaha/.local/swing/anaconda3/2023-01-11/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/lcrc/project/LCRC_for_DUNE/users/fathima/2x2_sim/run-larnd-sim/larnd-sim/./simulate_pixels.py", line 330, in run_simulation
    output_file.create_dataset("tracks", data=tracks)
  File "/gpfs/fs1/soft/swing/manual/anaconda3/2023-01-11/mconda3/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/gpfs/fs1/soft/swing/manual/anaconda3/2023-01-11/mconda3/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 165, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl, dapl=dapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 135, in h5py.h5d.create
ValueError: Unable to create dataset (name already exists)

real	0m31.376s
user	0m17.830s
sys	0m6.652s
